import os
import logging
import warnings
from Bio import PDB
from Bio.PDB import PDBList, PDBParser, PDBIO, Select
from Bio.PDB.PDBExceptions import PDBConstructionWarning
from Bio.SeqUtils import seq1

# Logging configuration for traceability
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
warnings.filterwarnings("ignore", category=PDBConstructionWarning)


class KinaseDatasetCurator:
    def __init__(self):
        """
        Initializes the curation environment, resolving absolute paths for the project
        root and defining the structural matrix kinase domain (wt and mut) to be
        downloaded and purified.
        """
        # 1. Dynamic resolution of the project root
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(script_dir)

        # 2. Explicit definition of the master data directory generated by the script
        self.data_dir = os.path.join(project_root, "data")

        # 3. Subdirectory topology anchored to the master directory
        self.dirs = {
            "raw": os.path.join(self.data_dir, "raw_pdb"),
            "processed": os.path.join(self.data_dir, "processed_pdb"),
            "fasta": os.path.join(self.data_dir, "fasta_sequences")
        }

        # 4. 2x2 Experimental matrix (Strictly Homo sapiens)
        self.targets = {
            # Axis A: EGFR
            "1XKK": ("A", "EGFR_WT"),
            "2ITV": ("A", "EGFR_Mutant_L858R"),
            # Axis B: BRAF
            "4WO5": ("A", "BRAF_WT"),
            "4MNF": ("A", "BRAF_Mutant_V600E")
        }
        self._setup_directories()

    def _setup_directories(self):
        """Generates the directory tree from scratch in the project root."""
        os.makedirs(self.data_dir, exist_ok=True)
        logging.info(f"Master directory verified/created at: {self.data_dir}")

        for name, path in self.dirs.items():
            os.makedirs(path, exist_ok=True)

        list_file = os.path.join(self.dirs["raw"], "PDB_files_list.txt")
        if not os.path.exists(list_file):
            with open(list_file, "w") as f:
                f.write("Log of downloaded PDB files:\n")

    def download_pdb(self, pdb_id):
        """
        Retrieves the specified crystallographic structure from the PDB
        via FTP, standardizes its nomenclature and registers the transaction.

        :param pdb_id: str (4-character alphanumeric PDB ID)

        :return: str (local path to the downloaded PDB file)
        """
        pdb_id = pdb_id.lower()
        download_dir = self.dirs["raw"]
        pdbl = PDBList(verbose=False)

        expected_pdb_path = os.path.join(download_dir, f"{pdb_id}.pdb")

        if os.path.exists(expected_pdb_path):
            logging.info(f"File {pdb_id}.pdb already exists locally. Skipping download.")
            return expected_pdb_path

        logging.info(f"Starting download for {pdb_id}...")
        file_path = pdbl.retrieve_pdb_file(
            pdb_code=pdb_id,
            file_format="pdb",
            pdir=download_dir,
            overwrite=True
        )

        if file_path:
            if file_path.endswith('.ent'):
                try:
                    os.rename(file_path, expected_pdb_path)
                    with open(os.path.join(download_dir, "PDB_files_list.txt"), "a") as f:
                        f.write(f"{pdb_id.upper()}\n")
                    return expected_pdb_path
                except Exception as e:
                    logging.error(f"Error renaming {file_path}: {str(e)}")
                    return file_path
            return file_path
        else:
            logging.error(f"Critical failure downloading: {pdb_id}")
            return None

    def purify_and_extract_fasta(self, pdb_path, pdb_id, chain_info):
        """
        Parses the raw PDB file, isolates the specific target chain, strictly filters out
        solvent molecules and heteroatoms and extracts the pure continuous AA sequence
        into a FASTA file.

        :param pdb_path: str (path to raw PDB file)
        :param pdb_id: str (4-character alphanumeric PDB ID)
        :param chain_info: tuple (target chain letter and biological state label)

        :return: None
        """
        target_chain, biological_state = chain_info
        pdb_id_upper = pdb_id.upper()
        processed_path = os.path.join(self.dirs["processed"], f"{pdb_id_upper}_{biological_state}_clean.pdb")
        fasta_path = os.path.join(self.dirs["fasta"], f"{pdb_id_upper}_{biological_state}.fasta")

        parser = PDBParser()
        structure = parser.get_structure(pdb_id_upper, pdb_path)

        class ChainAndProteinSelect(Select):
            def accept_chain(self, chain):
                return 1 if chain.id == target_chain else 0

            def accept_residue(self, residue):
                return 1 if residue.id[0] == ' ' and PDB.is_aa(residue, standard=True) else 0

        io = PDBIO()
        io.set_structure(structure)
        io.save(processed_path, ChainAndProteinSelect())
        logging.info(f"Purified structure generated: {processed_path}")

        clean_structure = parser.get_structure(f"{pdb_id_upper}_clean", processed_path)
        target_chain_obj = clean_structure[0][target_chain]
        sequence = "".join([seq1(residue.resname) for residue in target_chain_obj])

        with open(fasta_path, "w") as f:
            f.write(f">{pdb_id_upper}_{biological_state}_Homo_sapiens\n")
            for i in range(0, len(sequence), 80):
                f.write(f"{sequence[i:i + 80]}\n")

        logging.info(f"FASTA extracted for {biological_state}. Length: {len(sequence)} aa.")

    def execute_pipeline(self):
        logging.info("--- INITIATING STRUCTURAL CURATION PIPELINE ---")
        for pdb_id, chain_info in self.targets.items():
            logging.info(f"Processing target: {pdb_id} ({chain_info[1]})")

            pdb_path = self.download_pdb(pdb_id)

            if pdb_path:
                self.purify_and_extract_fasta(pdb_path, pdb_id, chain_info)

        logging.info("--- PIPELINE SUCCESSFULLY COMPLETED ---")


if __name__ == "__main__":
    curator = KinaseDatasetCurator()
    curator.execute_pipeline()