import os
import logging
import warnings
from Bio import PDB
from Bio.PDB import PDBList, PDBParser, PDBIO, Select
from Bio.PDB.PDBExceptions import PDBConstructionWarning
from Bio.SeqUtils import seq1

# Logging configuration for traceability
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
warnings.filterwarnings("ignore", category=PDBConstructionWarning)


class KinaseDatasetCurator:
    def __init__(self):
        """
        Initializes the curation environment, resolving absolute paths for the project
        root and defining the structural matrix kinase domain (wt and mut) to be
        downloaded and purified.
        """
        # 1. Dynamic resolution of the project root
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(script_dir)

        # 2. Explicit definition of the master data directory generated by the script
        self.data_dir = os.path.join(project_root, "data")

        # 3. Subdirectory topology anchored to the master directory
        self.dirs = {
            "raw": os.path.join(self.data_dir, "raw_pdb"),
            "processed": os.path.join(self.data_dir, "processed_pdb"),
            "fasta": os.path.join(self.data_dir, "fasta_sequences")
        }

        # 4. Experimental matrix

        self.targets = {
            "SRC": {
                "pdb_id": "2SRC", # Resolution: 1.5 A (Homo sapiens)
                "chain": "A",
                "mutations": {
                    "WT": [],
                    "E310A_Active": [("E", 310, "A")],
                    "T338G_Inhibitory": [("T", 338, "G")]
                }
            },
            "EGFR": {
                "pdb_id": "3POZ", # Resolution: 1.5 A (Homo sapiens)
                "chain": "A",
                "mutations": {
                    "WT": [],
                    "L858R": [("L", 858, "R")],
                    "L858R_T790M_Epistatic": [("L", 858, "R"), ("T", 790, "M")]
                }
            }
        }
        self._setup_directories()

    def _setup_directories(self):
        """
        Generates the directory tree from scratch in the project root.
        """
        os.makedirs(self.data_dir, exist_ok=True)
        for name, path in self.dirs.items():
            os.makedirs(path, exist_ok=True)
        logging.info(f"Directory structure: {self.dirs}")

    def download_pdb(self, pdb_id):
        """
        Retrieves the specified crystallographic structure from the PDB
        via FTP, standardizes its nomenclature and registers the transaction.

        :param pdb_id: str (4-character alphanumeric PDB ID)

        :return: str (local path to the downloaded PDB file)
        """
        pdb_id = pdb_id.lower()
        pdbl = PDBList(verbose=False)
        expected_pdb_path = os.path.join(self.dirs["raw"], f"{pdb_id}.pdb")

        if os.path.exists(expected_pdb_path):
            logging.info(f"[PDB] {pdb_id.upper()} already exists. Skipping download.")
            return expected_pdb_path

        file_path = pdbl.retrieve_pdb_file(
            pdb_code=pdb_id,
            file_format="pdb",
            pdir=self.dirs["raw"],
            overwrite=True
        )

        if file_path:
            if file_path.endswith('.ent'):
                try:
                    os.rename(file_path, expected_pdb_path)
                    list_file = os.path.join(self.dirs["raw"], "PDB_files_list.txt")
                    with open(list_file, "a") as f:
                        f.write(f"{pdb_id.upper()}\n")

                    logging.info(f"[PDB] Successfully downloaded and renamed {pdb_id.upper()}.")
                    return expected_pdb_path

                except Exception as e:
                    logging.error(f"[PDB Error] Error renaming {file_path}: {str(e)}")
                    return file_path
            return file_path
        else:
            logging.error(f"[PDB Critical] Critical failure downloading: {pdb_id.upper()}")
            return None

    def scaffold_and_sequences(self, kinase_name, config):
        """
        Purifies the 3D scaffold and extracts the FASTA sequences
        for the WT and mutant variants.

        :param kinase_name: str (e.g., 'SRC', 'EGFR')
        :param config: dict (target configuration: PDB ID, chain and mutation)

        :return: None
        """
        pdb_id = config["pdb_id"].upper()
        target_chain = config["chain"]
        raw_path = os.path.join(self.dirs["raw"], f"{pdb_id.lower()}.pdb")
        clean_path = os.path.join(self.dirs["processed"], f"{kinase_name}_scaffold_clean.pdb")

        parser = PDBParser()
        structure = parser.get_structure(pdb_id, raw_path)

        class ChainAndProteinSelect(Select):
            def accept_chain(self, chain):
                return 1 if chain.id == target_chain else 0

            def accept_residue(self, residue):
                return 1 if residue.id[0] == ' ' and PDB.is_aa(residue, standard=True) else 0

        # 1. Purify spatial scaffold
        io = PDBIO()
        io.set_structure(structure)
        io.save(clean_path, ChainAndProteinSelect())
        logging.info(f"[3D Scaffold] Purified and saved for {kinase_name}.")

        # 2. Extract sequence and map residue coordinates
        clean_structure = parser.get_structure(f"{kinase_name}_clean", clean_path)
        chain_obj = clean_structure[0][target_chain]
        res_map = {res.id[1]: seq1(res.resname) for res in chain_obj}
        res_indices = list(res_map.keys())

        # 3. In silico mutagenesis to generate differential FASTA files
        for mut_name, mutations in config["mutations"].items():
            fasta_path = os.path.join(self.dirs["fasta"], f"{kinase_name}_{mut_name}.fasta")

            mutated_sequence = res_map.copy()
            for (aa_orig, pos, aa_mut) in mutations:
                if pos in mutated_sequence and mutated_sequence[pos] == aa_orig:
                    mutated_sequence[pos] = aa_mut
                    logging.info(
                        f"[Mutagenesis] {kinase_name} {mut_name}: {aa_orig}{pos}{aa_mut} successfully applied.")
                else:
                    logging.warning(
                        f"[Mutagenesis Error] Position {pos} in {kinase_name} does not match native {aa_orig}.")

            # Assemble the final linear string
            final_seq = "".join([mutated_sequence[idx] for idx in res_indices])

            with open(fasta_path, "w") as f:
                f.write(f">{kinase_name}_{mut_name}\n")
                # Format sequence length conforming to FASTA 80-character strict limit
                for i in range(0, len(final_seq), 80):
                    f.write(f"{final_seq[i:i + 80]}\n")

            logging.info(f"[FASTA] Generated {kinase_name}_{mut_name} (Length: {len(final_seq)} aa).")

    def execute_pipeline(self):
        logging.info("--- INITIATING STRUCTURAL CURATION PIPELINE ---")
        for kinase, config in self.targets.items():
            logging.info(f"\nProcessing target system: {kinase}")
            if self.download_pdb(config["pdb_id"]):
                self.scaffold_and_sequences(kinase, config)
        logging.info("--- PIPELINE SUCCESSFULLY COMPLETED ---")


if __name__ == "__main__":
    curator = KinaseDatasetCurator()
    curator.execute_pipeline()